import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import Image from "next/image";

import "../src/styles/globals.css";
import { cn } from "@/utils/tailwind";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    montserrat.className,
                    "relative min-h-screen bg-main flex justify-center"
                )}
            >
                <div className="w-full px-6 py-20 lg:w-[1440px] xl:p-[120px]">
                    {children}
                </div>
                <Image
                    src="waves.svg"
                    alt="waves"
                    width={1920}
                    height={111}
                    className="absolute bottom-0 left-0"
                />
            </body>
        </html>
    );
}
